name: Terraform - Use Case 6

on:
  push:
    paths:
      - 'use-case-6/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: write  # Needed to commit README.md changes

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: use-case-6

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install terraform-docs
        run: |
          curl -sSL -o terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/v0.17.0/terraform-docs-v0.17.0-linux-amd64.tar.gz
          tar -xzf terraform-docs.tar.gz
          chmod +x terraform-docs
          sudo mv terraform-docs /usr/local/bin/

      - name: Generate Combined Terraform Docs
        run: |
          echo "# Terraform Use Case 6" > README.md
          echo "" >> README.md
          echo "## EC2 Module" >> README.md
          terraform-docs markdown modules/ec2 >> README.md

      - name: Commit updated Combined Terraform Docs
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "docs: update combined terraform-docs" || echo "No changes to commit"
          git push

      - name: Debug - List files
        run: ls -R

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::772693223647:role/OIDC
          aws-region: ap-south-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -recursive

      - name: Install Conftest
        run: |
          wget https://github.com/open-policy-agent/conftest/releases/download/v0.45.0/conftest_0.45.0_Linux_x86_64.tar.gz
          tar -xzf conftest_0.45.0_Linux_x86_64.tar.gz
          sudo mv conftest /usr/local/bin

      - name: Run OPA Conftest
        run: conftest test .

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan 
        run: terraform plan

      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch'
        run: terraform apply -auto-approve
