name: Terraform Deploy

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python (for Checkov)
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Checkov
        run: pip install checkov

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Set up TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - name: Initialize TFLint
        run: tflint --init
        working-directory: use-case-4

      - name: Run TFLint
        run: tflint -f compact
        working-directory: use-case-4

      - name: Terraform Format
        run: terraform fmt -check -recursive
        working-directory: use-case-4

      - name: Terraform Init
        run: terraform init
        working-directory: use-case-4

      - name: Terraform Validate
        run: terraform validate
        working-directory: use-case-4

      - name: Run Checkov Security Scan
        run: checkov -d . --framework terraform
        working-directory: use-case-4

      - name: Terraform Plan
        run: terraform plan
        working-directory: use-case-4

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: use-case-4
