name: Build and Push Docker Images to ECR

on:
  push:
    branches:
      - main
    paths:
      - 'patient-service/**'
      - 'appointment-service/**'
      - '.github/workflows/**'

env:
  AWS_REGION: us-east-1
  ACCOUNT_ID: 045911161916

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::045911161916:role/OIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build and Push patient-service
        working-directory: ./patient-service
        run: |
          docker build -t $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/patient-service:latest .
          docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/patient-service:latest

      - name: Build and Push appointment-service
        working-directory: ./appointment-service
        run: |
          docker build -t $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/appointment-service:latest .
          docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/appointment-service:latest
