name: Lambda Terraform OIDC Deployment

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  deploy:
    name: Terraform CI/CD with OIDC
    runs-on: ubuntu-latest

    environment: production

    defaults:
      run:
        working-directory: use-case-7

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install terraform-docs
        run: |
          curl -sSL -o terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/v0.17.0/terraform-docs-v0.17.0-linux-amd64.tar.gz
          tar -xzf terraform-docs.tar.gz
          chmod +x terraform-docs
          sudo mv terraform-docs /usr/local/bin/

      - name: Generate Combined Terraform Docs for All Modules
        run: |
          echo "# Terraform Modules Documentation" > README.md
          for dir in modules/*/; do
            echo -e "\n## Module: ${dir#*/}" >> README.md
            terraform-docs markdown "$dir" >> README.md
          done

      - name: Commit Combined README
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "docs: update combined Terraform README" || echo "No changes to commit"
          git push

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::427521931204:role/karthick_OIDC
          role-session-name: github-actions-session
          aws-region: ap-southeast-2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Create TFLint Config
        run: |
          mkdir -p ~/.tflint.d/plugins
          cat <<EOF > .tflint.hcl
          plugin "aws" {
          enabled = true
          version = "0.14.0"
          source  = "github.com/terraform-linters/tflint-ruleset-aws"
          region  = "ap-southeast-2"
           }
          EOF

      - name: Install TFLint and AWS Plugin
        run: |
          TFLINT_VERSION="v0.50.3"
          curl -sSL -o tflint.zip https://github.com/terraform-linters/tflint/releases/download/${TFLINT_VERSION}/tflint_${TFLINT_VERSION}_linux_amd64.zip
          unzip tflint.zip
          sudo mv tflint /usr/local/bin/
          rm tflint.zip
          tflint --init



      - name: Run TFLint
        run: tflint --recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -recursive

      - name: Install Conftest
        run: |
          wget https://github.com/open-policy-agent/conftest/releases/download/v0.45.0/conftest_0.45.0_Linux_x86_64.tar.gz
          tar -xzf conftest_0.45.0_Linux_x86_64.tar.gz
          sudo mv conftest /usr/local/bin

      - name: Run OPA Conftest
        run: conftest test .  

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
