name: Deploy Flask App to EKS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push Docker image
      env:
        ECR_REGISTRY: 045911161916.dkr.ecr.ap-south-1.amazonaws.com
        ECR_REPOSITORY: flask-app
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: v1.29.0

    - name: Configure kubeconfig
      run: |
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config

    - name: Deploy to EKS
      env:
        ECR_REGISTRY: 045911161916.dkr.ecr.ap-south-1.amazonaws.com
        ECR_REPOSITORY: flask-app
        IMAGE_TAG: ${{ github.sha }}
      run: |
        kubectl set image deployment/flask-deployment flask-app=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
