# .github/workflows/terraform_ecr.yml
name: Terraform ECR

on:
  workflow_dispatch:  # run manually once to create ECR repos

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::045911161916:role/OIDC
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init
        working-directory: ecr

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ecr
