name: Terraform Plan & Apply

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::772693223647:role/OIDC
          aws-region: ap-south-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan


        

     # - name: Install Checkov
     #    run: pip install checkov

     # - name: Run Checkov
     #  run: checkov -d use-case-6

     #  - name: Setup TFLint
     #    uses: terraform-linters/setup-tflint@v4
     #    with:
     #      tflint_version: latest

     #  - name: Create TFLint Config
     #    run: echo 'plugin "aws" { enabled = true region = "ap-south-1" }' > .tflint.hcl
     #    working-directory: use-case-6


     #  - name: Run TFLint
     #    run: |
     #      echo 'plugin "aws" { enabled = true region = "ap-south-1" }' > use-case-6/.tflint.hcl
     #      tflint --init
     #      tflint --recursive
     #    working-directory: use-case-6
        
       


          

